CREATE TABLE recordings (
    id UUID PRIMARY KEY,
    client_recording_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    session_id UUID NOT NULL,
    question_id UUID NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255),
    file_metadata JSONB,
    mime_type VARCHAR(100) NOT NULL,
    file_size_bytes BIGINT NOT NULL,
    sync_status VARCHAR(30) NOT NULL DEFAULT 'server_pending',
    transcript_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    analysis_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recordings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recordings_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recordings_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE RESTRICT,
    CONSTRAINT ck_recordings_file_size CHECK (file_size_bytes > 0),
    CONSTRAINT ck_recordings_sync_status CHECK (sync_status IN ('device_saved', 'server_pending', 'server_uploaded', 'analysis_completed', 'failed')),
    CONSTRAINT ck_recordings_transcript_status CHECK (transcript_status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT ck_recordings_analysis_status CHECK (analysis_status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE TABLE transcripts (
    id UUID PRIMARY KEY,
    recording_id UUID NOT NULL UNIQUE,
    transcript TEXT,
    duration_sec NUMERIC(8, 3),
    confidence NUMERIC(5, 4),
    language VARCHAR(20) NOT NULL DEFAULT 'ko',
    model_name VARCHAR(100),
    model_version VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    analyzed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_transcripts_recording FOREIGN KEY (recording_id) REFERENCES recordings (id) ON DELETE CASCADE,
    CONSTRAINT ck_transcripts_duration CHECK (duration_sec IS NULL OR duration_sec >= 0),
    CONSTRAINT ck_transcripts_confidence CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_transcripts_status CHECK (status IN ('pending', 'processing', 'completed', 'failed'))
);

CREATE TABLE answers (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL,
    question_id UUID NOT NULL,
    client_answer_id UUID NOT NULL,
    answer_text TEXT,
    recording_id UUID,
    transcript_id UUID,
    response_time_ms INTEGER,
    sync_status VARCHAR(20) NOT NULL DEFAULT 'server_uploaded',
    answered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_answers_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_answers_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_answers_recording FOREIGN KEY (recording_id) REFERENCES recordings (id) ON DELETE SET NULL,
    CONSTRAINT fk_answers_transcript FOREIGN KEY (transcript_id) REFERENCES transcripts (id) ON DELETE SET NULL,
    CONSTRAINT uq_answers_session_client_id UNIQUE (session_id, client_answer_id),
    CONSTRAINT ck_answers_content CHECK (answer_text IS NOT NULL OR recording_id IS NOT NULL OR transcript_id IS NOT NULL),
    CONSTRAINT ck_answers_response_time CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
    CONSTRAINT ck_answers_sync_status CHECK (sync_status IN ('server_pending', 'server_uploaded', 'failed'))
);

CREATE TABLE acoustic_analyses (
    id UUID PRIMARY KEY,
    recording_id UUID NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    acoustic_reference_score NUMERIC(8, 6),
    acoustic_flags JSONB,
    speech_rate NUMERIC(10, 4),
    pause_ratio NUMERIC(8, 6),
    energy_variability NUMERIC(10, 4),
    speech_stability NUMERIC(10, 4),
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_acoustic_analyses_recording FOREIGN KEY (recording_id) REFERENCES recordings (id) ON DELETE CASCADE,
    CONSTRAINT uq_acoustic_analyses_model UNIQUE (recording_id, model_name, model_version),
    CONSTRAINT ck_acoustic_reference_score CHECK (acoustic_reference_score IS NULL OR acoustic_reference_score BETWEEN 0 AND 1),
    CONSTRAINT ck_acoustic_pause_ratio CHECK (pause_ratio IS NULL OR pause_ratio BETWEEN 0 AND 1),
    CONSTRAINT ck_acoustic_speech_stability CHECK (speech_stability IS NULL OR speech_stability BETWEEN 0 AND 1)
);

CREATE TABLE cognitive_analyses (
    id UUID PRIMARY KEY,
    transcript_id UUID NOT NULL,
    acoustic_analysis_id UUID,
    user_id UUID NOT NULL,
    session_id UUID NOT NULL,
    question_id UUID,
    question_type VARCHAR(20) NOT NULL,
    fusion_mode VARCHAR(20) NOT NULL DEFAULT 'none',
    model_name VARCHAR(100) NOT NULL,
    model_version VARCHAR(100) NOT NULL,
    language_reference_score NUMERIC(8, 6),
    screening_reference_score NUMERIC(8, 6),
    label VARCHAR(30),
    risk_level VARCHAR(20),
    cognitive_flags JSONB,
    domain_scores JSONB,
    model_breakdown JSONB,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cognitive_analyses_transcript FOREIGN KEY (transcript_id) REFERENCES transcripts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cognitive_analyses_acoustic FOREIGN KEY (acoustic_analysis_id) REFERENCES acoustic_analyses (id) ON DELETE SET NULL,
    CONSTRAINT fk_cognitive_analyses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cognitive_analyses_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_cognitive_analyses_question FOREIGN KEY (question_id) REFERENCES questions (id) ON DELETE SET NULL,
    CONSTRAINT ck_cognitive_question_type CHECK (question_type IN ('orientation', 'memory', 'attention', 'language', 'emotion')),
    CONSTRAINT ck_cognitive_fusion_mode CHECK (fusion_mode IN ('none', 'average', 'weighted_average')),
    CONSTRAINT ck_cognitive_label CHECK (label IS NULL OR label IN ('normal', 'attention_required')),
    CONSTRAINT ck_cognitive_risk_level CHECK (risk_level IS NULL OR risk_level IN ('normal', 'caution', 'warning')),
    CONSTRAINT ck_cognitive_language_score CHECK (language_reference_score IS NULL OR language_reference_score BETWEEN 0 AND 1),
    CONSTRAINT ck_cognitive_screening_score CHECK (screening_reference_score IS NULL OR screening_reference_score BETWEEN 0 AND 1)
);

CREATE TABLE screening_results (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    screening_reference_score NUMERIC(8, 6),
    display_score NUMERIC(8, 2),
    score_max NUMERIC(8, 2),
    score_rate NUMERIC(8, 6),
    risk_level VARCHAR(20),
    display_label VARCHAR(100),
    recommendation TEXT,
    domain_scores JSONB,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_screening_results_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_screening_results_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_screening_results_status CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    CONSTRAINT ck_screening_results_reference_score CHECK (screening_reference_score IS NULL OR screening_reference_score BETWEEN 0 AND 1),
    CONSTRAINT ck_screening_results_score_max CHECK (score_max IS NULL OR score_max > 0),
    CONSTRAINT ck_screening_results_score_rate CHECK (score_rate IS NULL OR score_rate BETWEEN 0 AND 1),
    CONSTRAINT ck_screening_results_risk_level CHECK (risk_level IS NULL OR risk_level IN ('normal', 'caution', 'warning'))
);

CREATE TABLE session_summaries (
    id UUID PRIMARY KEY,
    session_id UUID NOT NULL UNIQUE,
    user_id UUID NOT NULL,
    summary TEXT,
    vocabulary_score NUMERIC(8, 2),
    keyword_flags JSONB,
    qa_count INTEGER NOT NULL DEFAULT 0,
    source_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_summaries_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_session_summaries_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_session_summaries_score CHECK (vocabulary_score IS NULL OR vocabulary_score BETWEEN 0 AND 100),
    CONSTRAINT ck_session_summaries_qa_count CHECK (qa_count >= 0),
    CONSTRAINT ck_session_summaries_status CHECK (source_status IN ('pending', 'completed', 'failed'))
);
